//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTDETAIL
    {
        public string CARTDETAIL_ID { get; set; }
        public string CART_ID { get; set; }
        public string PRODUCT_ID { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual CART CART { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
