//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORITE
    {
        public string FAVORITE_ID { get; set; }
        public string ACCOUNT_ID { get; set; }
        public string PRODUCT_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
